# This code is generated by text-davinci-003, a generative AI model by OpenAI

from tkinter import *

root = Tk() 

# Create a global variable to store our number
number = 0

def increment_number(): 
    global number 
    number += 1
    print(number)

# Create a button with "Increment Number" as its label 
btn = Button(root, text="Increment Number", command=increment_number)
btn.pack()

mainloop() 